### ISSUE TITLE
Can you provided a more memory-effective version. 

### ISSUE THREAD

**Issue by HalleyJiang** [DeepMIMO/DeepMIMO-codes#1]
Dear Ahmed, 

Thank you for providing this great dataset. I am using it in the project of my wireless communication class. But I cannot generate the dataset for the O1 scenario. The cell 'DeepMIMO_dataset' becomes very big, but my computer only has 16G RAM. So can you provide a more memory-effective version of generation code? Thanks

**Comment by DeepMIMO** [comment]
Thanks Hualie for your suggestion. We will release version 2 of the dataset soon that will be more memory-efficient!
