### ISSUE TITLE
Unable to read file './RayTracing Scenarios/O1_28/O1_28.params.mat'. No such file or directory.

### ISSUE THREAD

**Issue by OptComNet** [DeepMIMO/DeepMIMO-codes#2]

**Comment by DeepMIMO** [comment]
For the 'O1_28' scenario, please download the file named 'O1_28.zip' using [this link](https://drive.google.com/drive/folders/1quUFyRN_kkgc7dQG3xwhKZlNcu8aefbe?usp=sharing).

You will find the 'O1_28.params.mat' file inside the 'O1_28.zip' file.
