### ISSUE TITLE
For the 'O1_60' scenario, download the file named 'O1_60.zip' using this link.

### ISSUE THREAD

**Issue by vivianhjh** [DeepMIMO/DeepMIMO-codes#3]
The link of 'O1_60.zip' can not be available.Could you help me?

**Comment by MrSun94** [comment]
maybe you can download  it through VPN， it would be faster and steady

**Comment by vivianhjh** [comment]
Thank you very much!

**Comment by DeepMIMO** [comment]
The 'O1_60' link is checked and updated.

**Comment by yuexin249** [comment]
i am sorry but where can i found the O1_60 link , this really confuses me a lot. I can't open  [here](https://www.deepmimo.net/scenarios/o1-scenario/)
