### ISSUE TITLE
Error loading params file

### ISSUE THREAD

**Issue by Narasimhag** [DeepMIMO/DeepMIMO-codes#5]
Hi,

I am trying to load the file I1_2p4.params.mat stored relatively to file 'DeepMIMO_Dataset_Generator.m' at 'RayTracing Scenarios/I1_2p4/I1_2p4.params.mat'. But I get the following load error while doing that. 

`Error using load
Unable to read file './RayTracing Scenarios/I1_2p4/I1_2p4.params.mat'. No such
file or directory`

I'm new to MATLAB but is this looks like a file not found error. Is the path relative or do I need to set some path explicitly?

Thanks,
Narasimha

**Comment by Narasimhag** [comment]
I see a similar issue closed for O1 scenario. Is an alternate link to download 'I1_2p4' too?

**Comment by Narasimhag** [comment]
Found the solution to this issue. I was accessing it from wrong directory.

**Comment by rashiisingh** [comment]
> Found the solution to this issue. I was accessing it from wrong directory.

Sir, I'm facing the same issue, could you please tell me how you solved the problem.

Thanks,
Rashi
